package com.appdomicilios.catalog

import com.appdomicilios.model.OrderCategory

private fun expandedCatalog(vararg suggestions: String): List<String> {
    return suggestions
        .map(String::trim)
        .filter(String::isNotBlank)
        .distinct()
}

object ExpandedServiceCatalog {
    private val shoppingSubcategories = listOf(
        CatalogSubcategory(
            id = "supermercado",
            label = "Supermercado",
            suggestions = expandedCatalog(
                "Aceite",
                "Aceite de oliva",
                "Achocolatado",
                "Aguapanela",
                "Arroz",
                "Arveja en lata",
                "Atun",
                "Avena",
                "Azucar",
                "Cafe",
                "Caldo de gallina",
                "Canela",
                "Cereal",
                "Chocolate de mesa",
                "Chocolisto",
                "Compota",
                "Crema de leche",
                "Frijoles",
                "Gelatina",
                "Granola",
                "Harina de trigo",
                "Harina pan",
                "Harina para arepas",
                "Huevos",
                "Leche",
                "Leche deslactosada",
                "Leche en polvo",
                "Lentejas",
                "Mantequilla",
                "Margarina",
                "Mayonesa",
                "Mermelada",
                "Miel",
                "Mostaza",
                "Pan tajado",
                "Pasta",
                "Pimienta",
                "Pure de tomate",
                "Sal",
                "Salsa BBQ",
                "Salsa de tomate",
                "Salsa inglesa",
                "Sardinas",
                "Suavizante",
                "Vinagre",
            ),
        ),
        CatalogSubcategory(
            id = "tienda_barrio",
            label = "Tienda de barrio",
            suggestions = expandedCatalog(
                "Agua en bolsa",
                "Bon Bon Bum",
                "Cigarrillos",
                "Chocoramo",
                "Chocolate Jet",
                "Cocacola 400 ml",
                "Doritos",
                "Empanada",
                "Galletas Festival",
                "Galletas Saltin",
                "Gaseosa 1.5 litros",
                "Gaseosa 3 litros",
                "Helado",
                "Hielo",
                "Jugo Hit",
                "Mecato surtido",
                "Papas Margarita",
                "Pony Malta",
                "Rosquitas",
                "Servilletas",
                "Tinto preparado",
                "Yogurt bebible",
            ),
        ),
        CatalogSubcategory(
            id = "licores",
            label = "Licores",
            suggestions = expandedCatalog(
                "Aguardiente",
                "Agua tonica",
                "Cerveza Aguila",
                "Cerveza Andina",
                "Cerveza Club Colombia",
                "Cerveza Corona",
                "Cerveza Heineken",
                "Cerveza Poker",
                "Energizante",
                "Gaseosa para mezclar",
                "Hielo",
                "Jugo para mezclar",
                "Ron",
                "Ron Viejo de Caldas",
                "Tequila",
                "Vino blanco",
                "Vino espumoso",
                "Vino rosado",
                "Vino tinto",
                "Vodka",
                "Whisky",
            ),
        ),
        CatalogSubcategory(
            id = "drogueria",
            label = "Drogueria",
            suggestions = expandedCatalog(
                "Acetaminofen",
                "Alcohol",
                "Algodon",
                "Antiacido",
                "Antigripal",
                "Bloqueador solar",
                "Curitas",
                "Desinfectante",
                "Electrolit",
                "Esparadrapo",
                "Gasa",
                "Ibuprofeno",
                "Jarabe para la tos",
                "Loratadina",
                "Mascarillas",
                "Omeprazol",
                "Panal talla G",
                "Panal talla M",
                "Panal talla XG",
                "Panitos humedos",
                "Preservativos",
                "Sales de rehidratacion",
                "Suero oral",
                "Termometro",
                "Toallas higienicas",
                "Vitamina C",
                "Yodopovidona",
            ),
        ),
        CatalogSubcategory(
            id = "fruver",
            label = "Frutas y verduras",
            suggestions = expandedCatalog(
                "Aguacate",
                "Ajo",
                "Apio",
                "Banano",
                "Brocoli",
                "Cebolla cabezona",
                "Cebolla larga",
                "Cilantro",
                "Fresas",
                "Habichuela",
                "Lechuga",
                "Limon",
                "Mango",
                "Manzana",
                "Maracuya",
                "Naranja",
                "Papa criolla",
                "Papa pastusa",
                "Pepino",
                "Pimenton",
                "Platano",
                "Remolacha",
                "Tomate",
                "Uva",
                "Yuca",
                "Zanahoria",
            ),
        ),
        CatalogSubcategory(
            id = "carniceria",
            label = "Carniceria",
            suggestions = expandedCatalog(
                "Alas de pollo",
                "Carne de cerdo",
                "Carne para asar",
                "Carne para bistec",
                "Carne para sudado",
                "Carne molida",
                "Chuleta de cerdo",
                "Chorizo",
                "Costilla de res",
                "Costilla de cerdo",
                "Higado",
                "Hueso carnudo",
                "Lomo de cerdo",
                "Muslos de pollo",
                "Pechuga de pollo",
                "Pollo entero",
                "Salchicha",
                "Tocino",
            ),
        ),
        CatalogSubcategory(
            id = "panaderia",
            label = "Panaderia",
            suggestions = expandedCatalog(
                "Almojabana",
                "Arepas",
                "Bizcocho",
                "Croissant",
                "Donas",
                "Empanada de pollo",
                "Galletas",
                "Mogolla",
                "Pan alinado",
                "Pan campesino",
                "Pan de bono",
                "Pan de queso",
                "Pan frances",
                "Pastel de pollo",
                "Roscon",
                "Torta de chocolate",
                "Torta de vainilla",
            ),
        ),
        CatalogSubcategory(
            id = "aseo_hogar",
            label = "Aseo del hogar",
            suggestions = expandedCatalog(
                "Ambientador",
                "Blanqueador",
                "Bolsa para basura",
                "Cepillo de lavar",
                "Desengrasante",
                "Desinfectante piso",
                "Detergente en polvo",
                "Detergente liquido",
                "Esponja",
                "Guantes",
                "Jabon en barra",
                "Jabon lavaplatos",
                "Limpia vidrios",
                "Papel aluminio",
                "Papel higienico",
                "Recogedor",
                "Servilletas",
                "Trapero",
            ),
        ),
        CatalogSubcategory(
            id = "aseo_personal",
            label = "Aseo personal",
            suggestions = expandedCatalog(
                "Acondicionador",
                "Cepillo de dientes",
                "Crema corporal",
                "Crema dental",
                "Desodorante",
                "Enjuague bucal",
                "Jabon de tocador",
                "Maquina de afeitar",
                "Protector diario",
                "Shampoo",
                "Talco",
                "Toalla femenina",
            ),
        ),
        CatalogSubcategory(
            id = "bebidas_snacks",
            label = "Bebidas y snacks",
            suggestions = expandedCatalog(
                "Agua",
                "Avena liquida",
                "Brownie",
                "Chocolatina",
                "Galletas dulces",
                "Galletas saladas",
                "Gaseosa",
                "Jugo Hit",
                "Jugo natural",
                "Mecato",
                "Papas fritas",
                "Pony Malta",
                "Yogurt",
            ),
        ),
        CatalogSubcategory(
            id = "ferreteria",
            label = "Ferreteria",
            suggestions = expandedCatalog(
                "Alicate",
                "Bombillo LED",
                "Brocha",
                "Candado",
                "Cinta aislante",
                "Clavos",
                "Destornillador",
                "Extension electrica",
                "Lija",
                "Pegante PVC",
                "Pintura en spray",
                "Silicona",
                "Taco chazo",
                "Taladro",
                "Tornillos",
            ),
        ),
        CatalogSubcategory(
            id = "papeleria",
            label = "Papeleria",
            suggestions = expandedCatalog(
                "Block carta",
                "Cartulina",
                "Carpeta oficio",
                "Cinta pegante",
                "Cuaderno",
                "Esferos",
                "Foami",
                "Grapadora",
                "Hoja carta",
                "Lapices",
                "Marcadores",
                "Pegastick",
                "Resaltadores",
                "Tijeras",
            ),
        ),
        CatalogSubcategory(
            id = "mascotas",
            label = "Mascotas",
            suggestions = expandedCatalog(
                "Alimento para gato",
                "Alimento para perro",
                "Arena para gato",
                "Collar",
                "Correa",
                "Galletas para perro",
                "Juguete para mascota",
                "Panal trainer",
                "Shampoo para mascota",
                "Snacks para gato",
                "Snacks para perro",
            ),
        ),
        CatalogSubcategory(
            id = "tecnologia",
            label = "Tecnologia y accesorios",
            suggestions = expandedCatalog(
                "Audifonos",
                "Cable tipo C",
                "Cargador iPhone",
                "Cargador micro USB",
                "Cargador tipo C",
                "Memoria USB",
                "Pilas AA",
                "Pilas AAA",
                "Protector de pantalla",
                "Power bank",
            ),
        ),
    )

    private val restaurantSubcategories = listOf(
        CatalogSubcategory(
            id = "simply",
            label = "Simply",
            suggestions = emptyList(),
        ),
        CatalogSubcategory(
            id = "el_sinverguenza",
            label = "El Sinverguenza",
            suggestions = emptyList(),
        ),
        CatalogSubcategory(
            id = "la_carbonera",
            label = "La Carbonera",
            suggestions = emptyList(),
        ),
        CatalogSubcategory(
            id = "el_atajo",
            label = "El Atajo",
            suggestions = emptyList(),
        ),
        CatalogSubcategory(
            id = "el_sason_de_alejo",
            label = "El Sason de Alejo",
            suggestions = emptyList(),
        ),
        CatalogSubcategory(
            id = "el_fogon_de_oro",
            label = "El Fogon de Oro",
            suggestions = emptyList(),
        ),
    )

    private val tramitesSubcategories = listOf(
        CatalogSubcategory(
            id = "alcaldia",
            label = "Alcaldia",
            suggestions = expandedCatalog(
                "Certificado de residencia",
                "Certificado de estratificacion",
                "Impuesto predial",
                "Industria y comercio",
                "Paz y salvo municipal",
                "Peticion o radicado",
                "Radicar documento",
                "SISBEN",
                "Uso de suelo",
            ),
        ),
        CatalogSubcategory(
            id = "citas_medicas",
            label = "Citas medicas",
            suggestions = expandedCatalog(
                "Asignar cita general",
                "Asignar cita especializada",
                "Autorizar examen",
                "Autorizar procedimiento",
                "Pago de copago",
                "Radicar formula",
                "Reclamar autorizacion",
                "Reclamar medicamentos",
                "Reclamar resultados",
                "Solicitar historia clinica",
            ),
        ),
        CatalogSubcategory(
            id = "pagos",
            label = "Pagos",
            suggestions = expandedCatalog(
                "Administracion",
                "Cuota colegio",
                "Internet",
                "Pago de credito",
                "Pago de parqueadero",
                "Pago de seguro",
                "Recarga celular",
                "Recibo de agua",
                "Recibo de energia",
                "Recibo de gas",
                "Recibo de telefono",
                "TV cable",
            ),
        ),
        CatalogSubcategory(
            id = "notaria",
            label = "Notaria",
            suggestions = expandedCatalog(
                "Autenticacion",
                "Copia autentica",
                "Declaracion extrajuicio",
                "Registro civil",
                "Reconocimiento de firma",
                "Solicitud de copia",
            ),
        ),
        CatalogSubcategory(
            id = "bancarios",
            label = "Bancarios",
            suggestions = expandedCatalog(
                "Consignacion",
                "Pago de tarjeta",
                "Pago de credito",
                "Retiro por ventanilla",
                "Solicitud de extracto",
                "Transferencia asistida",
                "Turno para asesoria",
            ),
        ),
        CatalogSubcategory(
            id = "impresiones",
            label = "Impresiones y copias",
            suggestions = expandedCatalog(
                "Anillado",
                "Escanear documento",
                "Fotocopias",
                "Impresion a color",
                "Impresion blanco y negro",
                "Laminado",
                "Plastificar",
            ),
        ),
        CatalogSubcategory(
            id = "camara_comercio",
            label = "Camara de comercio",
            suggestions = expandedCatalog(
                "Certificado camara de comercio",
                "Consulta RUES",
                "Pago renovacion mercantil",
                "Radicar documento de empresa",
                "Reclamar certificado",
            ),
        ),
        CatalogSubcategory(
            id = "educacion",
            label = "Colegios y universidades",
            suggestions = expandedCatalog(
                "Entrega de documentos",
                "Pago de matricula",
                "Reclamar certificado de estudio",
                "Reclamar boletin",
                "Solicitar constancia",
            ),
        ),
        CatalogSubcategory(
            id = "mensajeria",
            label = "Mensajeria y paqueteria",
            suggestions = expandedCatalog(
                "Enviar sobre",
                "Entregar documento",
                "Pago de guia",
                "Radicar paquete",
                "Recoger encomienda",
            ),
        ),
        CatalogSubcategory(
            id = "transito",
            label = "Transito y movilidad",
            suggestions = expandedCatalog(
                "Pago comparendo",
                "Reclamar licencia",
                "Reclamar documento de vehiculo",
                "Solicitud de cita transito",
                "Tramite SOAT",
            ),
        ),
        CatalogSubcategory(
            id = "juzgados",
            label = "Juzgados y fiscalia",
            suggestions = expandedCatalog(
                "Entrega de memorial",
                "Radicar documento",
                "Reclamar copia de expediente",
                "Solicitar turno",
            ),
        ),
    )

    private val envioSubcategories = listOf(
        CatalogSubcategory(
            id = "sobres",
            label = "Sobres",
            suggestions = expandedCatalog(
                "Sobre carta",
                "Sobre manila",
                "Sobre con contrato",
                "Sobre con factura",
                "Sobre con papeles personales",
            ),
        ),
        CatalogSubcategory(
            id = "documentos",
            label = "Documentos",
            suggestions = expandedCatalog(
                "Carpeta con documentos",
                "Certificados",
                "Contrato",
                "Documentos de vehiculo",
                "Examenes medicos",
                "Factura",
                "Formula medica",
                "Papeles personales",
                "Resultados de laboratorio",
            ),
        ),
        CatalogSubcategory(
            id = "paquetes_pequenos",
            label = "Paquetes pequenos",
            suggestions = expandedCatalog(
                "Accesorios",
                "Celular",
                "Cosmeticos",
                "Medicamentos",
                "Repuesto pequeno",
                "Ropa doblada",
                "Zapatos",
            ),
        ),
        CatalogSubcategory(
            id = "paquetes_medianos",
            label = "Paquetes medianos",
            suggestions = expandedCatalog(
                "Caja de zapatos",
                "Mercancia",
                "Mercado pequeno",
                "Paquete de ropa",
                "Regalo",
                "Repuesto mediano",
            ),
        ),
        CatalogSubcategory(
            id = "cajas",
            label = "Cajas",
            suggestions = expandedCatalog(
                "Caja pequena",
                "Caja mediana",
                "Caja grande",
                "Caja con encomienda",
                "Caja con mercancia",
            ),
        ),
        CatalogSubcategory(
            id = "fragil",
            label = "Fragil",
            suggestions = expandedCatalog(
                "Cristaleria",
                "Equipo electronico",
                "Portatil",
                "Producto delicado",
                "Regalo fragil",
                "Vajilla",
            ),
        ),
    )

    fun subcategoriesFor(category: OrderCategory): List<CatalogSubcategory> {
        return when (category) {
            OrderCategory.SHOPPING -> shoppingSubcategories
            OrderCategory.RESTAURANTS -> restaurantSubcategories
            OrderCategory.TRAMITES -> tramitesSubcategories
            OrderCategory.ENVIOS -> envioSubcategories
            else -> emptyList()
        }
    }

    fun suggestionsFor(
        category: OrderCategory,
        subcategoryId: String?,
    ): List<String> {
        return subcategoriesFor(category)
            .firstOrNull { it.id == subcategoryId }
            ?.suggestions
            .orEmpty()
    }
}
